### ISSUE TITLE
Error: template: netdata/templates/secrets.yaml:1:21

### ISSUE THREAD

**Issue by AchuM** [netdata/helmchart#384]
Hello, 

I'm getting the following error when installing with helm. 

`Error: template: netdata/templates/secrets.yaml:1:21: executing "netdata/templates/secrets.yaml" at <include "netdata.parent.configs.secret" .>: error calling include: template: netdata/templates/_helpers.tpl:125:28: executing "netdata.parent.configs.secret" at <eq $config.storedType "secret">: error calling eq: incompatible types for comparison`

Any idea how to fix this logic?

**Comment by ilyam8** [comment]
Hi, @AchuM. This issue is a duplicate of #378 and #368.

**Comment by AchuM** [comment]
Thanks @ilyam8 But I'm using helm `v3.9.2`

**Comment by ilyam8** [comment]
Then 3.9.2 is not enough, should work with 3.12.0+

**Comment by AchuM** [comment]
Thanks. I'll upgrade to 3.12.0+ then.

**Comment by ilyam8** [comment]
Just tested using [alpine/helm](https://hub.docker.com/r/alpine/helm) Docker images - I get this error only with 3.7.2, no problem with 3.8.0+.
